###########################################################
#
#                       数据源参数配置-druid
#
###########################################################
initialSize: 5
minIdle: 5
maxIdle: 100
maxActive: 20
maxWait: 60000
timeBetweenEvictionRunsMillis: 60000
minEvictableIdleTimeMillis: 300000

# 数据源配置
sharding:
  jdbc:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@//duyunchao.cezegjv1a5ih.rds.cn-north-1.amazonaws.com.cn:1521/duyunchao
        username: duyunchao
        password: duyunchao

        initialSize: ${initialSize}
        minIdle: ${minIdle}
        maxActive: ${maxActive}
        maxWait: ${maxWait}
        validationQuery: SELECT 1 FROM DUAL
        timeBetweenEvictionRunsMillis: ${timeBetweenEvictionRunsMillis}
        minEvictableIdleTimeMillis: ${minEvictableIdleTimeMillis}
#分表配置
    config:
      props:
        sql:
          show: true
      sharding:
        default-data-source-name: ds0
        tables:
          order:
            actual-data-nodes: ds0.order_$->{0..2},ds0.order_m1001,ds0.order_m1002,ds0.order_m1003
            tbindex: 3
            table-strategy:
              standard:
                precise-algorithm-class-name: com.cmb.demo.shardingtable.config.OrderInfoShardingAlgorithm
                sharding-column: mid
            tableMapping:
              m1001: m1001
              m1002: m1002
              m1003: m1003
              m1004: m1003

spring:
  main:
    allow-bean-definition-overriding: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

